development:
  cloud_name: dtupbjqib
  api_key: '688123113582317'
  api_secret: _h6aE-IofWdG_FyKCkUbR_IRV-M
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dtupbjqib
  api_key: '688123113582317'
  api_secret: _h6aE-IofWdG_FyKCkUbR_IRV-M
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dtupbjqib
  api_key: '688123113582317'
  api_secret: _h6aE-IofWdG_FyKCkUbR_IRV-M
  enhance_image_tag: true
  static_image_support: false

# development:
#   cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) %>
#   api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) %>
#   api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) %>
#   enhance_image_tag: true
#   static_image_support: false
# production:
#   cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) %>
#   api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) %>
#   api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) %>
#   enhance_image_tag: true
#   static_image_support: true
# test:
#   cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) %>
#   api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) %>
#   api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) %>
#   enhance_image_tag: true
#   static_image_support: false